### PR TITLE
2 new commands

### PR DESCRIPTION
**Pull request by TakenMC**
I added NeovimProjectLoadHist and NeovimProjectLoad which allow you to open a project from your history or all projects with completions

### CODE REVIEW

**Comment by TakenMC** [comment]
I don't know how you used panvimdoc so i couldn't generate the docs as well

you could add that at the bottom under contributing section

**Comment by coffebar** [comment]
You can edit `doc/neovim-project.txt` file directly to add these commands to the docs.
Take as an example those commands that already there, so as not to make a mistake with the formatting.

**Comment by coffebar** [comment]
This feature looks useful. But there is a problem. A project path shortened to one word cannot serve as a unique project identifier. I can't include this feature as is, because it will look like a bug to users. Think about how to fix it, or you will have to give up

**Comment by coffebar** [comment]
It will be terribly inconvenient if someone wants to use this command for scripting, i.e. pass the project as an argument to the command via a script. 
Wouldn't it be better to just leave the full path to the project?

**Comment by coffebar** [comment]
In the future, pay attention to the format for the name of the commits. 
It will be useful to read https://www.conventionalcommits.org/en/v1.0.0/

**Comment by TakenMC** [comment]
oops didn't see the recent message about the commits
but now it's using the paths instead
image

**Comment by coffebar** [comment]
It works for me. Thanks for contribution

**Comment by TakenMC** [comment]
no problem

**Pull request merged**
